<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PCAGenomicSignatures - Contents • PCAGenomicSignatures</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="PCAGenomicSignatures - Contents">
<meta property="og:description" content="PCAGenomicSignatures">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">PCAGenomicSignatures</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.0.1</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/PCAGenomicSignatures_Contents.html">PCAGenomicSignatures - Contents</a>
    </li>
    <li>
      <a href="../articles/Quickstart.html">PCAGenomicSignatures - Quickstart</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="PCAGenomicSignatures_Contents_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>PCAGenomicSignatures - Contents</h1>
                        <h4 class="author">Sehyun Oh</h4>
            
            <h4 class="date">July 15, 2020</h4>
      
      
      <div class="hidden name"><code>PCAGenomicSignatures_Contents.Rmd</code></div>

    </div>

    
    
<div id="setup" class="section level1">
<h1 class="hasAnchor">
<a href="#setup" class="anchor"></a>Setup</h1>
<div id="install-and-load-package" class="section level2">
<h2 class="hasAnchor">
<a href="#install-and-load-package" class="anchor"></a>Install and load package</h2>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="kw">if</span> (!<span class="fu"><a href="https://rdrr.io/r/base/library.html">require</a></span>(<span class="st">"devtools"</span>)) {
  <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span>(<span class="st">"devtools"</span>)
}
<span class="kw pkg">devtools</span><span class="kw ns">::</span><span class="fu"><a href="https://devtools.r-lib.org//reference/remote-reexports.html">install_github</a></span>(<span class="st">"shbrief/PCAGenomicSignatures"</span>)</pre></body></html></div>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">PCAGenomicSignatures</span>)</pre></body></html></div>
</div>
<div id="download-pcamodel" class="section level2">
<h2 class="hasAnchor">
<a href="#download-pcamodel" class="anchor"></a>Download PCAmodel</h2>
<p>Currently, you can download PCAGenomicSignatures (711.2 MB) from Google Cloud bucket using AnVIL Bioconductor/R package. This model is built from 1,399 studies (containing 75,433 samples) and 7,951 common genes from each of 1,399 study’s top 90% varying genes based on thier study-level standard deviation.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="kw">if</span> (!<span class="fu"><a href="https://rdrr.io/r/base/ns-load.html">requireNamespace</a></span>(<span class="st">"BiocManager"</span>, <span class="kw">quietly</span> <span class="kw">=</span> <span class="fl">TRUE</span>))
    <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span>(<span class="st">"BiocManager"</span>)

<span class="kw pkg">BiocManager</span><span class="kw ns">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html">install</a></span>(<span class="st">"AnVIL"</span>)</pre></body></html></div>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">AnVIL</span>)
<span class="no">wd</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/getwd.html">getwd</a></span>()
<span class="fu"><a href="https://rdrr.io/pkg/AnVIL/man/gsutil.html">gsutil_cp</a></span>(<span class="st">"gs://genomic_signatures/refinebioRseq_PCAmodel_hclust.rds"</span>, <span class="no">wd</span>)
<span class="no">PCAmodel</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/readRDS.html">readRDS</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/file.path.html">file.path</a></span>(<span class="no">wd</span>, <span class="st">"refinebioRseq_PCAmodel_hclust.rds"</span>))
<span class="no">PCAmodel</span></pre></body></html></div>
<pre><code>#&gt; class: PCAGenomicSignatures 
#&gt; dim: 7951 12436 
#&gt; metadata(6): cluster size ... MeSH_freq updateNote
#&gt; assays(1): model
#&gt; rownames(7951): 5S_rRNA 7SK ... SLC16A3 SLC38A2
#&gt; rowData names(0):
#&gt; colnames(12436): PCcluster1 PCcluster2 ... PCcluster12435
#&gt;   PCcluster12436
#&gt; colData names(3): PCcluster studies silhouetteWidth
#&gt; trainingData(2): PCAsummary MeSH
#&gt; trainingData names(1399): DRP000499 ERP023890 ... SRP188526 SRP189762</code></pre>
</div>
<div id="quick-summary-of-main-information" class="section level2">
<h2 class="hasAnchor">
<a href="#quick-summary-of-main-information" class="anchor"></a>Quick Summary of main information</h2>
<ul>
<li>model(PCAmodel) : avgLoading matrix<br>
</li>
<li>studies(PCAmodel) : a list of character vectors, containing studies in each loading<br>
</li>
<li>gsea(PCAmodel) : a list of gseaResult objects of each loading (coming soon!)<br>
</li>
<li>mesh(PCAmodel) : a list of data frames containing MeSH information associated with each study<br>
</li>
<li>PCAsummary(PCAmodel) : a list of matrix (3 by 20) containing PCA summary of each study</li>
</ul>
</div>
</div>
<div id="accessors" class="section level1">
<h1 class="hasAnchor">
<a href="#accessors" class="anchor"></a>Accessors</h1>
<div id="pcclusters-avgloadings-model" class="section level2">
<h2 class="hasAnchor">
<a href="#pcclusters-avgloadings-model" class="anchor"></a>PCclusters/ avgLoadings/ model</h2>
<p>Average loadings (= avgLoading = PCclusters) is the main part of GenomicSignatures, serving as an index connecting new datasets and the existing database used to build it. You can access it through <code><a href="../reference/PCAGenomicSignatures.html">PCAGenomicSignatures::model</a></code> (equivalent of <code><a href="https://rdrr.io/pkg/SummarizedExperiment/man/SummarizedExperiment-class.html">SummarizedExperiment::assay</a></code>). Rows are genes and columns are avgLoading vectors.</p>
<p>Here, PCAmodel consists of 7,951 genes and 12,436 PCclusters.</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span>(<span class="fu"><a href="../reference/PCAGenomicSignatures.html">model</a></span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1] "matrix" "array"</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span>(<span class="fu"><a href="../reference/PCAGenomicSignatures.html">model</a></span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1]  7951 12436</span>
<span class="fu"><a href="../reference/PCAGenomicSignatures.html">model</a></span>(<span class="no">PCAmodel</span>)[<span class="fl">1</span>:<span class="fl">4</span>, <span class="fl">1</span>:<span class="fl">4</span>]
<span class="co">#&gt;            PCcluster1   PCcluster2    PCcluster3   PCcluster4</span>
<span class="co">#&gt; 5S_rRNA  0.0014536985  0.007203501  6.277371e-03 -0.019858317</span>
<span class="co">#&gt; 7SK     -0.0028296151 -0.004445093  4.778814e-03  0.008085082</span>
<span class="co">#&gt; A1CF     0.0026854929  0.007484668  3.097421e-03  0.001099322</span>
<span class="co">#&gt; A2M      0.0003207426 -0.002994387 -6.339345e-05  0.003361415</span></pre></body></html></div>
</div>
<div id="metadata" class="section level2">
<h2 class="hasAnchor">
<a href="#metadata" class="anchor"></a>Metadata</h2>
<p>Metadata slot of the PCAGenomicSignatures object contains information related to the model buildling.</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="fu">metadata</span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1] "cluster"    "size"       "k"          "n"          "MeSH_freq" </span>
<span class="co">#&gt; [6] "updateNote"</span></pre></body></html></div>
<p><code>cluster</code> contains the cluster membership of each PCs from training dataset and <code>size</code> is the integer vector with the length of clusters, containing the size of each cluster. <code>k</code> is the number of clusters and <code>n</code> is the number of top PCs kept from each study in training dataset. <code>MeSH_freq</code> is the information on the frequency of MeSH terms assigned to training dataset. You can see that MeSH term ‘Humans’ and ‘RNA-seq’ are top ranked, which is very expected because the training dataset of this model is Human RNA sequencing. <code>updateNote</code> gives a brief character of this model.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="fu">metadata</span>(<span class="no">PCAmodel</span>)$<span class="no">cluster</span>)
<span class="co">#&gt; DRP000499.PC1 DRP000499.PC2 DRP000499.PC3 DRP000499.PC4 DRP000499.PC5 </span>
<span class="co">#&gt;             1             2             3             4             5 </span>
<span class="co">#&gt; DRP000499.PC6 </span>
<span class="co">#&gt;             6</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="fu">metadata</span>(<span class="no">PCAmodel</span>)$<span class="no">size</span>)
<span class="co">#&gt; [1] 7 7 6 7 2 2</span>
<span class="fu">metadata</span>(<span class="no">PCAmodel</span>)$<span class="no">k</span>
<span class="co">#&gt; [1] 12436</span>
<span class="fu">metadata</span>(<span class="no">PCAmodel</span>)$<span class="no">n</span>
<span class="co">#&gt; [1] 20</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span>(<span class="fu">metadata</span>(<span class="no">PCAmodel</span>)$<span class="no">MeSH_freq</span>)
<span class="co">#&gt; </span>
<span class="co">#&gt;                 Humans                RNA-Seq          Transcriptome </span>
<span class="co">#&gt;                   1163                    591                    576 </span>
<span class="co">#&gt;                    RNA Whole Exome Sequencing        Sequencing, RNA </span>
<span class="co">#&gt;                    372                    284                    277</span>
<span class="fu"><a href="../reference/PCAGenomicSignatures.html">updateNote</a></span>(<span class="no">PCAmodel</span>)
<span class="co">#&gt; [1] "1,399 refine.bio studies/ no control/ no annotation-based gene subset"</span></pre></body></html></div>
</div>
<div id="studies-in-each-loading" class="section level2">
<h2 class="hasAnchor">
<a href="#studies-in-each-loading" class="anchor"></a>Studies in each loading</h2>
<p>You can find which studies are in each cluster using <code><a href="../reference/PCAGenomicSignatures.html">studies(x)</a></code> method. Output is a list with the length of clusters, where each element is a character vector containing the name of studies in each cluster.</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="../reference/PCAGenomicSignatures.html">studies</a></span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1] 12436</span>
<span class="fu"><a href="../reference/PCAGenomicSignatures.html">studies</a></span>(<span class="no">PCAmodel</span>)[<span class="fl">1</span>:<span class="fl">3</span>]
<span class="co">#&gt; $Cl12436_01</span>
<span class="co">#&gt; [1] "DRP000499" "ERP023890" "SRP028336" "SRP047192" "SRP069760" "SRP107366"</span>
<span class="co">#&gt; [7] "SRP109805"</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $Cl12436_02</span>
<span class="co">#&gt; [1] "DRP000499" "ERP109789" "SRP072417" "SRP074544" "SRP100477" "SRP114518"</span>
<span class="co">#&gt; [7] "SRP136742"</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; $Cl12436_03</span>
<span class="co">#&gt; [1] "DRP000499" "SRP043364" "SRP126289" "SRP126741" "SRP145663" "SRP145862"</span></pre></body></html></div>
</div>
<div id="mesh-terms-for-each-study" class="section level2">
<h2 class="hasAnchor">
<a href="#mesh-terms-for-each-study" class="anchor"></a>MeSH terms for each study</h2>
<p>You can find MeSH terms associated with each study using <code><a href="../reference/PCAGenomicSignatures.html">mesh(x)</a></code> method. Output is a list with the length of studies in training dataset, where each element is a data frame containing the assigned MeSH terms and the detail of them. The last column <code>bagOfWords</code> is the frequency of that MeSH term in the whole training dataset.</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="../reference/PCAGenomicSignatures.html">mesh</a></span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1] 1399</span>
<span class="fu"><a href="../reference/PCAGenomicSignatures.html">mesh</a></span>(<span class="no">PCAmodel</span>)[<span class="fl">1</span>]
<span class="co">#&gt; $DRP000499</span>
<span class="co">#&gt;         score identifier               name</span>
<span class="co">#&gt; 1604326  4303  DRP000499             Humans</span>
<span class="co">#&gt; 1522299  2196  DRP000499      Base Sequence</span>
<span class="co">#&gt; 585485   1779  DRP000499 Chromosome Mapping</span>
<span class="co">#&gt; 112012   1338  DRP000499      Genome, Human</span>
<span class="co">#&gt;                                                                                                                                                     explanation</span>
<span class="co">#&gt; 1604326 Forced Leaf Node Lookup:humans, Genome, Human, CT Treecode Lookup: G05.360.340.350 (Genome, Human), CT Text Lookup: homo sapiens, CT Text Lookup: human</span>
<span class="co">#&gt; 1522299                                                                                                                              RtM via: genome sequencing</span>
<span class="co">#&gt; 585485                                                                                                                               RtM via: genome sequencing</span>
<span class="co">#&gt; 112012                                                                                                                                   RtM via: Genome, Human</span>
<span class="co">#&gt;         bagOfWords</span>
<span class="co">#&gt; 1604326       1163</span>
<span class="co">#&gt; 1522299        188</span>
<span class="co">#&gt; 585485           2</span>
<span class="co">#&gt; 112012          35</span></pre></body></html></div>
</div>
<div id="pca-summary" class="section level2">
<h2 class="hasAnchor">
<a href="#pca-summary" class="anchor"></a>PCA summary</h2>
<p>You can find the PCA summary of each study using <code><a href="../reference/PCAGenomicSignatures.html">PCAsummary(x)</a></code> method. Output is a list with the length of studies, where each element is a matrix containing PCA summary results with SD/Variance/Cumulative.</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span>(<span class="fu"><a href="../reference/PCAGenomicSignatures.html">PCAsummary</a></span>(<span class="no">PCAmodel</span>))
<span class="co">#&gt; [1] 1399</span>
<span class="fu"><a href="../reference/PCAGenomicSignatures.html">PCAsummary</a></span>(<span class="no">PCAmodel</span>)[<span class="fl">1</span>]
<span class="co">#&gt; $DRP000499</span>
<span class="co">#&gt;            DRP000499.PC1 DRP000499.PC2 DRP000499.PC3 DRP000499.PC4</span>
<span class="co">#&gt; SD            59.0820395   16.41547959    6.57735211   6.138468877</span>
<span class="co">#&gt; Variance       0.8294267    0.06402863    0.01027943   0.008953383</span>
<span class="co">#&gt; Cumulative     0.8294267    0.89345534    0.90373477   0.912688157</span>
<span class="co">#&gt;            DRP000499.PC5 DRP000499.PC6 DRP000499.PC7 DRP000499.PC8</span>
<span class="co">#&gt; SD           6.029335660     5.8395765    5.45528370   5.186589571</span>
<span class="co">#&gt; Variance     0.008637856     0.0081027    0.00707134   0.006391913</span>
<span class="co">#&gt; Cumulative   0.921326013     0.9294287    0.93650005   0.942891966</span>
<span class="co">#&gt;            DRP000499.PC9 DRP000499.PC10 DRP000499.PC11 DRP000499.PC12</span>
<span class="co">#&gt; SD           5.109390133    4.771454262    4.739276238    4.647818869</span>
<span class="co">#&gt; Variance     0.006203049    0.005409643    0.005336925    0.005132931</span>
<span class="co">#&gt; Cumulative   0.949095015    0.954504658    0.959841583    0.964974514</span>
<span class="co">#&gt;            DRP000499.PC13 DRP000499.PC14 DRP000499.PC15 DRP000499.PC16</span>
<span class="co">#&gt; SD            4.595424773    4.447827854    4.404402705    4.309704712</span>
<span class="co">#&gt; Variance      0.005017858    0.004700705    0.004609365    0.004413286</span>
<span class="co">#&gt; Cumulative    0.969992372    0.974693077    0.979302442    0.983715728</span>
<span class="co">#&gt;            DRP000499.PC17 DRP000499.PC18 DRP000499.PC19 DRP000499.PC20</span>
<span class="co">#&gt; SD            4.294590080    4.189794081    4.150554112    3.912577804</span>
<span class="co">#&gt; Variance      0.004382385    0.004171117    0.004093353    0.003637416</span>
<span class="co">#&gt; Cumulative    0.988098113    0.992269230    0.996362584    1.000000000</span></pre></body></html></div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Sehyun Oh.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
